#pragma once

static const char kDashboardPage[] =
  "<header><h1>Aquaculture Monitoring</h1>"
  "<div class='status' id='last-update'>waiting...</div></header>"
  "<main>"
  "<section class='cards'>"
  "<div class='card'><h3>pH</h3>"
  "<div class='metric'><span>Tank 1</span><strong id='ph1'>--</strong></div>"
  "<div class='metric'><span>Tank 2</span><strong id='ph2'>--</strong></div>"
  "</div>"
  "<div class='card'><h3>O2 (mg/L)</h3>"
  "<div class='metric'><span>Tank 1</span><strong id='o21'>--</strong></div>"
  "<div class='metric'><span>Tank 2</span><strong id='o22'>--</strong></div>"
  "</div>"
  "<div class='card'><h3>Temperature (C)</h3>"
  "<div class='metric'><span>Tank 1</span><strong id='t1'>--</strong></div>"
  "<div class='metric'><span>Tank 2</span><strong id='t2'>--</strong></div>"
  "</div>"
  "<div class='card'><h3>Levels</h3>"
  "<div class='metric'><span>Tank 1</span><strong id='l1'>--</strong></div>"
  "<div class='metric'><span>Tank 2</span><strong id='l2'>--</strong></div>"
  "</div>"
  "<div class='card'><h3>Blowers</h3>"
  "<div class='blowers'>"
  "<div id='blower-dot' class='dot'></div><strong id='blower-state'>--</strong>"
  "</div>"
  "<div class='blower-inputs'>"
  "<label>A0 threshold (V)<input type='number' step='0.01' id='thr-a0' value='0.30'/></label>"
  "<span id='a0-volts' class='ads-val'>-- V</span>"
  "</div>"
  "<div class='blower-inputs'>"
  "<label>A1 threshold (V)<input type='number' step='0.01' id='thr-a1' value='0.30'/></label>"
  "<span id='a1-volts' class='ads-val'>-- V</span>"
  "</div>"
  "<div class='blower-inputs'>"
  "<label>Notify delay (s)<input type='number' step='1' min='1' max='600' id='thr-delay' value='10'/></label>"
  "<span class='ads-raw'>stable</span>"
  "</div>"
  "<div class='blower-inputs'>"
  "<label class='alarm-toggle'><input type='checkbox' id='blower-alarm'/> Alarma blowers</label>"
  "<span class='ads-raw'>Relay 0 output</span>"
  "</div>"
  "<div class='blower-actions'>"
  "<button id='thr-apply' type='button'>Apply</button>"
  "</div>"
  "</div>"
  "<div class='card ads-card'><h3>ADS1115</h3>"
  "<div class='ads-row'><label><input type='checkbox' class='ads-toggle' data-ch='0'/> A0</label>"
  "<span class='ads-val' id='ads-v0'>-- V</span><span class='ads-raw' id='ads-r0'>raw --</span></div>"
  "<div class='ads-row'><label><input type='checkbox' class='ads-toggle' data-ch='1'/> A1</label>"
  "<span class='ads-val' id='ads-v1'>-- V</span><span class='ads-raw' id='ads-r1'>raw --</span></div>"
  "<div class='ads-row'><label><input type='checkbox' class='ads-toggle' data-ch='2'/> A2</label>"
  "<span class='ads-val' id='ads-v2'>-- V</span><span class='ads-raw' id='ads-r2'>raw --</span></div>"
  "<div class='ads-row'><label><input type='checkbox' class='ads-toggle' data-ch='3'/> A3</label>"
  "<span class='ads-val' id='ads-v3'>-- V</span><span class='ads-raw' id='ads-r3'>raw --</span></div>"
  "</div>"
  "<div class='card uart-card'><h3>UART1 Control</h3>"
  "<div class='uart-actions'>"
  "<button id='uart-get-status' type='button'>Get Status</button>"
  "<button id='uart-get-last' type='button'>Get Last</button>"
  "<button id='uart-auto' type='button'>Auto Measure</button>"
  "</div>"
  "<div class='uart-auto'>"
  "<label>Auto interval (min)<input type='number' min='1' step='1' id='uart-auto-interval' value='5'/></label>"
  "<label class='uart-toggle'><input type='checkbox' id='uart-auto-enable'/> Auto enable</label>"
  "</div>"
  "<div class='uart-note'>Responses are logged in console.</div>"
  "</div>"
  "<div class='card clock-card'><h3>Clock</h3>"
  "<div class='clock-time' id='clock-time'>--</div>"
  "<div class='clock-status' id='clock-status'>sync pending</div>"
  "</div>"
  "<div class='card sdlogs-card'><h3>SD Logs</h3>"
  "<div class='sdlogs-actions'>"
  "<button id='sdlogs-uart' type='button'>UART</button>"
  "<button id='sdlogs-level' type='button'>Level</button>"
  "<button id='sdlogs-refresh' type='button'>Refresh</button>"
  "<button id='sdlogs-clear' type='button'>Clear Logs</button>"
  "</div>"
  "<div class='sdlogs-output' id='sdlogs-output'>--</div>"
  "</div>"
  "<div class='card ubidots-card'><h3>Ubidots Publish</h3>"
  "<div class='ubidots-row'>"
  "<label>Interval (min)<input type='number' min='1' step='1' id='ubidots-interval' value='5'/></label>"
  "<button id='ubidots-apply' type='button'>Apply</button>"
  "</div>"
  "<div class='uart-note'>Applies to telemetry publish frequency.</div>"
  "</div>"
  "<div class='card pcf-card'><h3>PCF IO</h3>"
  "<div class='pcf-block'><div class='pcf-title'>DI</div>"
  "<div class='pcf-grid'>"
  "<div class='pcf-io pcf-in' data-pin='0'><span>DI 0</span><i class='pcf-dot'></i></div>"
  "<div class='pcf-io pcf-in' data-pin='1'><span>DI 1</span><i class='pcf-dot'></i></div>"
  "<div class='pcf-io pcf-in' data-pin='2'><span>DI 2</span><i class='pcf-dot'></i></div>"
  "<div class='pcf-io pcf-in' data-pin='3'><span>DI 3</span><i class='pcf-dot'></i></div>"
  "<div class='pcf-io pcf-in' data-pin='4'><span>DI 4</span><i class='pcf-dot'></i></div>"
  "<div class='pcf-io pcf-in' data-pin='5'><span>DI 5</span><i class='pcf-dot'></i></div>"
  "<div class='pcf-io pcf-in' data-pin='6'><span>DI 6</span><i class='pcf-dot'></i></div>"
  "<div class='pcf-io pcf-in' data-pin='7'><span>DI 7</span><i class='pcf-dot'></i></div>"
  "</div></div>"
  "<div class='pcf-block'><div class='pcf-title'>DO</div>"
  "<div class='pcf-grid'>"
  "<button class='pcf-io pcf-out' data-pin='0' type='button'><span>Relay-0</span><i class='pcf-dot'></i></button>"
  "<button class='pcf-io pcf-out' data-pin='1' type='button'><span>Relay-1</span><i class='pcf-dot'></i></button>"
  "<button class='pcf-io pcf-out' data-pin='2' type='button'><span>Relay-2</span><i class='pcf-dot'></i></button>"
  "<button class='pcf-io pcf-out' data-pin='3' type='button'><span>Relay-3</span><i class='pcf-dot'></i></button>"
  "<button class='pcf-io pcf-out' data-pin='4' type='button'><span>DO 4</span><i class='pcf-dot'></i></button>"
  "<button class='pcf-io pcf-out' data-pin='5' type='button'><span>DO 5</span><i class='pcf-dot'></i></button>"
  "<button class='pcf-io pcf-out' data-pin='6' type='button'><span>DO 6</span><i class='pcf-dot'></i></button>"
  "<button class='pcf-io pcf-out' data-pin='7' type='button'><span>DO 7</span><i class='pcf-dot'></i></button>"
  "</div></div>"
  "</div>"
  "<div class='card i2c-card'><h3>I2C Scan</h3>"
  "<div class='i2c-row'>"
  "<button id='i2c-scan' type='button'>Scan</button>"
  "<div class='i2c-status' id='i2c-status'>idle</div>"
  "</div>"
  "<div class='i2c-list' id='i2c-list'>No devices</div>"
  "</div>"
  "<div class='card espnow-card'><h3>ESP-NOW Tanks</h3>"
  "<div class='espnow-row'>"
  "<label>Tank 1 MAC<input id='espnow-mac-1' type='text' placeholder='AA:BB:CC:DD:EE:FF'/></label>"
  "<button id='espnow-save-1' type='button'>Save</button>"
  "<button id='espnow-req-1' type='button'>Request</button>"
  "</div>"
  "<div class='espnow-row'>"
  "<label>Tank 2 MAC<input id='espnow-mac-2' type='text' placeholder='AA:BB:CC:DD:EE:FF'/></label>"
  "<button id='espnow-save-2' type='button'>Save</button>"
  "<button id='espnow-req-2' type='button'>Request</button>"
  "</div>"
  "<div class='espnow-self'>This device: <span id='espnow-self'>--</span></div>"
  "<div class='espnow-self'>Channel: <span id='espnow-channel'>--</span></div>"
  "<div class='espnow-auto'>"
  "<label>Auto interval (min)<input type='number' min='1' step='1' id='espnow-auto-interval' value='5'/></label>"
  "<label class='espnow-toggle'><input type='checkbox' id='espnow-auto-enable'/> Auto enable</label>"
  "</div>"
  "<div class='espnow-status' id='espnow-status'>idle</div>"
  "</div>"
  "</section>"
  "<section class='charts'>"
  "<div class='chart'><h4>pH</h4>"
  "<div class='legend'><span class='legend-item'><i class='swatch swatch-a'></i>Tank 1</span>"
  "<span class='legend-item'><i class='swatch swatch-b'></i>Tank 2</span></div>"
  "<canvas id='chart-ph'></canvas></div>"
  "<div class='chart'><h4>O2</h4>"
  "<div class='legend'><span class='legend-item'><i class='swatch swatch-a'></i>Tank 1</span>"
  "<span class='legend-item'><i class='swatch swatch-b'></i>Tank 2</span></div>"
  "<canvas id='chart-o2'></canvas></div>"
  "<div class='chart'><h4>Temperature</h4>"
  "<div class='legend'><span class='legend-item'><i class='swatch swatch-a'></i>Tank 1</span>"
  "<span class='legend-item'><i class='swatch swatch-b'></i>Tank 2</span></div>"
  "<canvas id='chart-temp'></canvas></div>"
  "<div class='chart'><h4>Levels</h4>"
  "<div class='legend'><span class='legend-item'><i class='swatch swatch-a'></i>Tank 1</span>"
  "<span class='legend-item'><i class='swatch swatch-b'></i>Tank 2</span></div>"
  "<canvas id='chart-level'></canvas></div>"
  "</section>"
  "</main>";
