#pragma once

static const char kDashboardPage[] =
  "<header><h1>Aquaculture Monitoring</h1>"
  "<div class='status' id='last-update'>waiting...</div></header>"
  "<main>"
  "<section class='cards'>"
  "<div class='card'><h3>pH</h3>"
  "<div class='metric'><span>Tank 1</span><strong id='ph1'>--</strong></div>"
  "<div class='metric'><span>Tank 2</span><strong id='ph2'>--</strong></div>"
  "</div>"
  "<div class='card'><h3>O2 (mg/L)</h3>"
  "<div class='metric'><span>Tank 1</span><strong id='o21'>--</strong></div>"
  "<div class='metric'><span>Tank 2</span><strong id='o22'>--</strong></div>"
  "</div>"
  "<div class='card'><h3>Temperature (C)</h3>"
  "<div class='metric'><span>Tank 1</span><strong id='t1'>--</strong></div>"
  "<div class='metric'><span>Tank 2</span><strong id='t2'>--</strong></div>"
  "</div>"
  "<div class='card'><h3>Levels</h3>"
  "<div class='metric'><span>Tank 1</span><strong id='l1'>--</strong></div>"
  "<div class='metric'><span>Tank 2</span><strong id='l2'>--</strong></div>"
  "</div>"
  "<div class='card'><h3>Blowers</h3>"
  "<div class='blowers'><div id='blower-dot' class='dot'></div>"
  "<strong id='blower-state'>--</strong></div>"
  "</div>"
  "<div class='card ads-card'><h3>ADS1115</h3>"
  "<div class='ads-row'><label><input type='checkbox' class='ads-toggle' data-ch='0'/> A0</label>"
  "<span class='ads-val' id='ads-v0'>-- V</span><span class='ads-raw' id='ads-r0'>raw --</span></div>"
  "<div class='ads-row'><label><input type='checkbox' class='ads-toggle' data-ch='1'/> A1</label>"
  "<span class='ads-val' id='ads-v1'>-- V</span><span class='ads-raw' id='ads-r1'>raw --</span></div>"
  "<div class='ads-row'><label><input type='checkbox' class='ads-toggle' data-ch='2'/> A2</label>"
  "<span class='ads-val' id='ads-v2'>-- V</span><span class='ads-raw' id='ads-r2'>raw --</span></div>"
  "<div class='ads-row'><label><input type='checkbox' class='ads-toggle' data-ch='3'/> A3</label>"
  "<span class='ads-val' id='ads-v3'>-- V</span><span class='ads-raw' id='ads-r3'>raw --</span></div>"
  "</div>"
  "</section>"
  "<section class='charts'>"
  "<div class='chart'><h4>pH</h4>"
  "<div class='legend'><span class='legend-item'><i class='swatch swatch-a'></i>Tank 1</span>"
  "<span class='legend-item'><i class='swatch swatch-b'></i>Tank 2</span></div>"
  "<canvas id='chart-ph'></canvas></div>"
  "<div class='chart'><h4>O2</h4>"
  "<div class='legend'><span class='legend-item'><i class='swatch swatch-a'></i>Tank 1</span>"
  "<span class='legend-item'><i class='swatch swatch-b'></i>Tank 2</span></div>"
  "<canvas id='chart-o2'></canvas></div>"
  "<div class='chart'><h4>Temperature</h4>"
  "<div class='legend'><span class='legend-item'><i class='swatch swatch-a'></i>Tank 1</span>"
  "<span class='legend-item'><i class='swatch swatch-b'></i>Tank 2</span></div>"
  "<canvas id='chart-temp'></canvas></div>"
  "<div class='chart'><h4>Levels</h4>"
  "<div class='legend'><span class='legend-item'><i class='swatch swatch-a'></i>Tank 1</span>"
  "<span class='legend-item'><i class='swatch swatch-b'></i>Tank 2</span></div>"
  "<canvas id='chart-level'></canvas></div>"
  "</section>"
  "</main>";
