#pragma once

static const char kDashboardScript[] =
  "<script>"
  "var lastUpdateEl=document.getElementById('last-update');"
  "var ph1=document.getElementById('ph1');var ph2=document.getElementById('ph2');"
  "var o21=document.getElementById('o21');var o22=document.getElementById('o22');"
  "var t1=document.getElementById('t1');var t2=document.getElementById('t2');"
  "var l1=document.getElementById('l1');var l2=document.getElementById('l2');"
  "var blowerDot=document.getElementById('blower-dot');"
  "var blowerState=document.getElementById('blower-state');"
  "var thrA0=document.getElementById('thr-a0');"
  "var thrA1=document.getElementById('thr-a1');"
  "var thrApply=document.getElementById('thr-apply');"
  "var thrDelay=document.getElementById('thr-delay');"
  "var blowerAlarm=document.getElementById('blower-alarm');"
  "var uartGetStatus=document.getElementById('uart-get-status');"
  "var uartGetLast=document.getElementById('uart-get-last');"
  "var uartAuto=document.getElementById('uart-auto');"
  "var i2cScanBtn=document.getElementById('i2c-scan');"
  "var i2cStatus=document.getElementById('i2c-status');"
  "var i2cList=document.getElementById('i2c-list');"
  "var pcfInitialized=false;"
  "var isEditingA0=false;var isEditingA1=false;var isEditingDelay=false;"
  "var a0Volts=document.getElementById('a0-volts');"
  "var a1Volts=document.getElementById('a1-volts');"
  "var consoleEl=document.getElementById('console');"
  "var consoleStatus=document.getElementById('console-status');"
  "var adsInitialized=false;"
  "var series={ph1:[],ph2:[],o21:[],o22:[],t1:[],t2:[],l1:[],l2:[]};"
  "var maxPoints=60;"

  "function pushPoint(key,val){var arr=series[key];arr.push(val);if(arr.length>maxPoints){arr.shift();}}"

  "function drawChart(canvasId,a,b,colorA,colorB){"
  "var canvas=document.getElementById(canvasId);if(!canvas){return;}"
  "var ctx=canvas.getContext('2d');var w=canvas.clientWidth;var h=canvas.clientHeight;"
  "canvas.width=w;canvas.height=h;ctx.clearRect(0,0,w,h);"
  "ctx.strokeStyle='#1f242b';ctx.lineWidth=1;ctx.strokeRect(0,0,w,h);"
  "function findMinMax(arrA,arrB){var min=Infinity;var max=-Infinity;"
  "for(var i=0;i<arrA.length;i++){if(arrA[i]<min){min=arrA[i];}if(arrA[i]>max){max=arrA[i];}}"
  "for(var j=0;j<arrB.length;j++){if(arrB[j]<min){min=arrB[j];}if(arrB[j]>max){max=arrB[j];}}"
  "if(min===Infinity){min=0;max=1;}if(min===max){min-=1;max+=1;}return {min:min,max:max};}"
  "var bounds=findMinMax(a,b);"
  "function drawLine(data,color){if(data.length<2){return;}ctx.strokeStyle=color;ctx.beginPath();"
  "for(var i=0;i<data.length;i++){var x=i*(w/(maxPoints-1));"
  "var y=h-((data[i]-bounds.min)/(bounds.max-bounds.min))*h;"
  "if(i===0){ctx.moveTo(x,y);}else{ctx.lineTo(x,y);}}ctx.stroke();}"
  "drawLine(a,colorA);drawLine(b,colorB);"
  "}"

  "function updateCharts(){"
  "drawChart('chart-ph',series.ph1,series.ph2,'#67d4ff','#9ad9ff');"
  "drawChart('chart-o2',series.o21,series.o22,'#67d4ff','#9ad9ff');"
  "drawChart('chart-temp',series.t1,series.t2,'#67d4ff','#9ad9ff');"
  "drawChart('chart-level',series.l1,series.l2,'#67d4ff','#9ad9ff');"
  "}"

  "function updateCards(d){"
  "ph1.textContent=d.phTank1.toFixed(2);ph2.textContent=d.phTank2.toFixed(2);"
  "o21.textContent=d.o2Tank1.toFixed(2);o22.textContent=d.o2Tank2.toFixed(2);"
  "t1.textContent=d.tempTank1.toFixed(2);t2.textContent=d.tempTank2.toFixed(2);"
  "l1.textContent=d.levelTank1.toFixed(2);l2.textContent=d.levelTank2.toFixed(2);"
  "blowerState.textContent=d.stateBlowers?'ON':'OFF';"
  "if(d.stateBlowers){blowerDot.classList.add('on');}else{blowerDot.classList.remove('on');}"
  "}"

  "function updateAds(mask,channels){"
  "for(var i=0;i<4;i++){"
  "var toggle=document.querySelector('.ads-toggle[data-ch=\"'+i+'\"]');"
  "if(toggle){toggle.checked=(mask&(1<<i))!==0;}"
  "var vEl=document.getElementById('ads-v'+i);"
  "var rEl=document.getElementById('ads-r'+i);"
  "var ch=channels[i]||{};"
  "if(vEl){vEl.textContent=ch.valid?ch.volts.toFixed(3)+' V':'-- V';}"
  "if(rEl){rEl.textContent=ch.valid?('raw '+ch.raw):'raw --';}"
  "}"
  "if(!adsInitialized){initAdsToggles();adsInitialized=true;}"
  "}"

  "function initAdsToggles(){"
  "var toggles=document.querySelectorAll('.ads-toggle');"
  "toggles.forEach(function(t){t.addEventListener('change',applyAdsMask);});"
  "}"

  "function applyAdsMask(){"
  "var mask=0;"
  "document.querySelectorAll('.ads-toggle').forEach(function(t){"
  "var ch=parseInt(t.getAttribute('data-ch'))||0;"
  "if(t.checked){mask|=(1<<ch);}"
  "});"
  "fetch('/api/analog/enable',{method:'POST',headers:{'Content-Type':'application/json'},"
  "body:JSON.stringify({enabledMask:mask})}).then(function(r){return r.json();})"
  ".then(function(d){if(d&&typeof d.enabledMask!=='undefined'){updateAds(d.enabledMask,[]);}});"
  "}"

  "function updateBlowers(d){"
  "if(thrA0 && !isEditingA0){thrA0.value=d.a0.threshold.toFixed(2);}"
  "if(thrA1 && !isEditingA1){thrA1.value=d.a1.threshold.toFixed(2);}"
  "if(thrDelay && !isEditingDelay){thrDelay.value=d.delaySec;}"
  "if(blowerAlarm){blowerAlarm.checked=!!d.alarmEnabled;}"
  "if(a0Volts){a0Volts.textContent=(d.a0.valid?d.a0.volts.toFixed(3):'--')+' V';}"
  "if(a1Volts){a1Volts.textContent=(d.a1.valid?d.a1.volts.toFixed(3):'--')+' V';}"
  "if(d.belowThreshold){blowerState.textContent='OFF';}"
  "else{blowerState.textContent=d.state?'ON':'OFF';}"
  "blowerDot.classList.remove('on');blowerDot.classList.remove('warn');"
  "if(d.belowThreshold){blowerDot.classList.add('warn');}"
  "else if(d.state){blowerDot.classList.add('on');}"
  "}"

  "function setPcfState(el,value){"
  "if(!el){return;}"
  "if(value){el.classList.add('on');}else{el.classList.remove('on');}"
  "el.setAttribute('data-state',value?'1':'0');"
  "}"

  "function updatePcf(d){"
  "if(!d||!d.di||!d.do){return;}"
  "for(var i=0;i<8;i++){"
  "var inEl=Array.from(document.querySelectorAll('.pcf-in')).find(function(el){return el.getAttribute('data-pin')==i;});"
  "var outEl=Array.from(document.querySelectorAll('.pcf-out')).find(function(el){return el.getAttribute('data-pin')==i;});"
  "var inVal=!!d.di[i];var outVal=!!d.do[i];"
  "setPcfState(inEl,inVal);"
  "setPcfState(outEl,outVal);"
  "}"
  "if(!pcfInitialized){initPcfOutputs();pcfInitialized=true;}"
  "}"

  "function initPcfOutputs(){"
  "document.querySelectorAll('.pcf-out').forEach(function(btn){"
  "btn.addEventListener('click',function(){"
  "var pin=parseInt(btn.getAttribute('data-pin'))||0;"
  "var state=btn.getAttribute('data-state')==='1'?1:0;"
  "var next=state?0:1;"
  "postPcfDo(pin,next);"
  "});"
  "});"
  "}"

  "function postPcfDo(pin,value){"
  "fetch('/api/pcf/do',{method:'POST',headers:{'Content-Type':'application/json'},"
  "body:JSON.stringify({pin:pin,value:value})}).then(function(r){return r.json();})"
  ".then(function(d){if(d&&d.ok){fetchPcf();}});"
  "}"

  "function renderI2c(d){"
  "if(!i2cStatus||!i2cList){return;}"
  "if(!d||!d.ok){i2cStatus.textContent='error';i2cList.textContent='Scan failed';return;}"
  "var devices=d.devices||[];"
  "i2cStatus.textContent='ok';"
  "if(!devices.length){i2cList.textContent='No devices';return;}"
  "var labels=devices.map(function(addr){"
  "var hex=addr.toString(16).toUpperCase();"
  "if(hex.length<2){hex='0'+hex;}"
  "return '0x'+hex;"
  "});"
  "i2cList.textContent=labels.join(', ');"
  "}"

  "function scanI2c(){"
  "if(i2cStatus){i2cStatus.textContent='scanning...';}"
  "fetch('/api/i2c/scan').then(function(r){return r.json();}).then(function(d){renderI2c(d);})"
  ".catch(function(){if(i2cStatus){i2cStatus.textContent='error';}if(i2cList){i2cList.textContent='Scan failed';}});"
  "}"

  "function postBlowers(){"
  "var a0=parseFloat(thrA0.value)||0;"
  "var a1=parseFloat(thrA1.value)||0;"
  "var delay=parseInt(thrDelay.value)||10;"
  "fetch('/api/blowers',{method:'POST',headers:{'Content-Type':'application/json'},"
  "body:JSON.stringify({a0:a0,a1:a1,delaySec:delay})}).then(function(r){return r.json();})"
  ".then(function(){isEditingA0=false;isEditingA1=false;isEditingDelay=false;fetchBlowers();});"
  "}"

  "function postBlowerAlarm(){"
  "if(!blowerAlarm){return;}"
  "var enabled=blowerAlarm.checked?1:0;"
  "fetch('/api/blowers',{method:'POST',headers:{'Content-Type':'application/json'},"
  "body:JSON.stringify({alarmEnabled:enabled})}).then(function(r){return r.json();})"
  ".then(function(){fetchBlowers();});"
  "}"

  "function fetchBlowers(){"
  "fetch('/api/blowers').then(function(r){return r.json();}).then(function(d){updateBlowers(d);});"
  "}"

  "function fetchPcf(){"
  "fetch('/api/pcf/state').then(function(r){return r.json();}).then(function(d){updatePcf(d);});"
  "}"

  "function fetchDashboard(){"
  "fetch('/api/dashboard').then(function(r){return r.json();}).then(function(d){"
  "updateCards(d);"
  "pushPoint('ph1',d.phTank1);pushPoint('ph2',d.phTank2);"
  "pushPoint('o21',d.o2Tank1);pushPoint('o22',d.o2Tank2);"
  "pushPoint('t1',d.tempTank1);pushPoint('t2',d.tempTank2);"
  "pushPoint('l1',d.levelTank1);pushPoint('l2',d.levelTank2);"
  "updateCharts();"
  "lastUpdateEl.textContent='updated '+new Date().toLocaleTimeString();"
  "}).catch(function(){lastUpdateEl.textContent='update failed';});"
  "}"

  "function fetchAnalog(){"
  "fetch('/api/analog').then(function(r){return r.json();}).then(function(d){"
  "updateAds(d.enabledMask,d.channels||[]);"
  "});"
  "}"

  "function sendUart(op){"
  "fetch('/api/uart/cmd?op='+encodeURIComponent(op),{method:'POST'})"
  ".then(function(r){return r.json();})"
  ".then(function(d){if(!d||!d.ok){consoleEl.textContent+='UART error\\n';}})"
  ".catch(function(){consoleEl.textContent+='UART error\\n';});"
  "}"

  "var ws=new WebSocket('ws://'+location.hostname+':81/');"
  "ws.onopen=function(){consoleStatus.textContent='connected';};"
  "ws.onerror=function(){consoleStatus.textContent='error';};"
  "ws.onclose=function(){consoleStatus.textContent='disconnected';};"
  "ws.onmessage=function(e){if(consoleEl.textContent==='Waiting for messages...'){consoleEl.textContent='';}"
  "consoleEl.textContent+=e.data+'\\n';consoleEl.scrollTop=consoleEl.scrollHeight;};"

  "fetchDashboard();fetchAnalog();fetchBlowers();"
  "fetchPcf();"
  "setInterval(fetchDashboard,2000);"
  "setInterval(fetchAnalog,2000);"
  "setInterval(fetchBlowers,2000);"
  "setInterval(fetchPcf,1000);"
  "if(thrA0){thrA0.addEventListener('focus',function(){isEditingA0=true;});"
  "thrA0.addEventListener('blur',function(){isEditingA0=false;});}"
  "if(thrA1){thrA1.addEventListener('focus',function(){isEditingA1=true;});"
  "thrA1.addEventListener('blur',function(){isEditingA1=false;});}"
  "if(thrDelay){thrDelay.addEventListener('focus',function(){isEditingDelay=true;});"
  "thrDelay.addEventListener('blur',function(){isEditingDelay=false;});}"
  "if(thrApply){thrApply.addEventListener('click',postBlowers);}"
  "if(blowerAlarm){blowerAlarm.addEventListener('change',postBlowerAlarm);}"
  "if(uartGetStatus){uartGetStatus.addEventListener('click',function(){sendUart('get_status');});}"
  "if(uartGetLast){uartGetLast.addEventListener('click',function(){sendUart('get_last');});}"
  "if(uartAuto){uartAuto.addEventListener('click',function(){sendUart('auto_measure');});}"
  "if(i2cScanBtn){i2cScanBtn.addEventListener('click',scanI2c);}"
  "</script>";
