#pragma once

static const char kDashboardStyle[] =
  "<style>"
  ":root{--bg:#0f1114;--panel:#15191e;--card:#1a1f25;--muted:#9aa4ad;--text:#e7ecef;"
  "--accent:#67d4ff;--ok:#47d17c;--warn:#f5b24a;}"
  "*{box-sizing:border-box;}"
  "body{margin:0;background:var(--bg);color:var(--text);font-family:ui-monospace,SFMono-Regular,"
  "Menlo,Monaco,Consolas,'Liberation Mono','Courier New',monospace;}"
  "header{padding:16px 20px;border-bottom:1px solid #222830;display:flex;align-items:center;"
  "justify-content:space-between;background:#0e1216;position:sticky;top:0;z-index:5;}"
  "header h1{margin:0;font-size:16px;letter-spacing:0.08em;text-transform:uppercase;color:var(--muted);}"
  ".status{font-size:12px;color:var(--muted);}"
  "main{padding:18px 20px 0;}"
  ".cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px;}"
  ".card{background:var(--card);border:1px solid #242a2f;border-radius:10px;padding:12px;"
  "box-shadow:0 10px 25px rgba(0,0,0,0.25);}"
  ".card h3{margin:0 0 8px 0;font-size:12px;color:var(--muted);text-transform:uppercase;letter-spacing:0.06em;}"
  ".metric{display:flex;justify-content:space-between;align-items:center;margin:4px 0;font-size:14px;}"
  ".metric span{color:var(--muted);}"
  ".blowers{display:flex;align-items:center;gap:8px;font-size:14px;}"
  ".dot{width:10px;height:10px;border-radius:50%;background:var(--warn);}"
  ".dot.on{background:var(--ok);}"
  ".ads-card{grid-column:span 2;}"
  ".ads-row{display:grid;grid-template-columns:64px 1fr 1fr;gap:8px;align-items:center;"
  "font-size:12px;margin:6px 0;}"
  ".ads-row label{display:flex;align-items:center;gap:6px;color:var(--muted);}"
  ".ads-val{color:var(--accent);font-weight:600;}"
  ".ads-raw{color:var(--muted);text-align:right;}"
  ".charts{display:grid;grid-template-columns:repeat(auto-fit,minmax(320px,1fr));gap:12px;margin-top:16px;}"
  ".chart{background:var(--panel);border:1px solid #242a2f;border-radius:10px;padding:12px;position:relative;}"
  ".chart h4{margin:0 0 6px 0;font-size:12px;color:var(--muted);text-transform:uppercase;letter-spacing:0.06em;}"
  ".legend{display:flex;gap:10px;flex-wrap:wrap;font-size:11px;color:var(--muted);margin-bottom:6px;}"
  ".legend-item{display:flex;align-items:center;gap:6px;}"
  ".swatch{width:10px;height:10px;border-radius:50%;display:inline-block;}"
  ".swatch-a{background:#67d4ff;}"
  ".swatch-b{background:#9ad9ff;}"
  "canvas{width:100%;height:160px;background:#0f1318;border-radius:6px;}"
  ".console-wrap{margin-top:18px;border-top:1px solid #222830;background:#0b0d10;padding:12px 20px 18px;}"
  ".console-head{display:flex;align-items:center;justify-content:space-between;color:var(--muted);"
  "font-size:12px;margin-bottom:8px;}"
  "#console{height:220px;overflow:auto;background:#0f1216;border:1px solid #242a2f;border-radius:8px;"
  "padding:10px;white-space:pre-wrap;font-size:12px;}"
  "</style>";
