#pragma once

static const char kDashboardScript[] =
  "<script>"
  "var lastUpdateEl=document.getElementById('last-update');"
  "var ph1=document.getElementById('ph1');var ph2=document.getElementById('ph2');"
  "var o21=document.getElementById('o21');var o22=document.getElementById('o22');"
  "var t1=document.getElementById('t1');var t2=document.getElementById('t2');"
  "var l1=document.getElementById('l1');var l2=document.getElementById('l2');"
  "var blowerDot=document.getElementById('blower-dot');"
  "var blowerState=document.getElementById('blower-state');"
  "var thrA0=document.getElementById('thr-a0');"
  "var thrA1=document.getElementById('thr-a1');"
  "var thrApply=document.getElementById('thr-apply');"
  "var thrDelay=document.getElementById('thr-delay');"
  "var blowerAlarm=document.getElementById('blower-alarm');"
  "var uartGetStatus=document.getElementById('uart-get-status');"
  "var uartGetLast=document.getElementById('uart-get-last');"
  "var uartAuto=document.getElementById('uart-auto');"
  "var uartAutoInterval=document.getElementById('uart-auto-interval');"
  "var uartAutoEnable=document.getElementById('uart-auto-enable');"
  "var ubidotsInterval=document.getElementById('ubidots-interval');"
  "var ubidotsApply=document.getElementById('ubidots-apply');"
  "var clockTime=document.getElementById('clock-time');"
  "var clockStatus=document.getElementById('clock-status');"
  "var sdLogsUart=document.getElementById('sdlogs-uart');"
  "var sdLogsLevel=document.getElementById('sdlogs-level');"
  "var sdLogsRefresh=document.getElementById('sdlogs-refresh');"
  "var sdLogsClear=document.getElementById('sdlogs-clear');"
  "var sdLogsOutput=document.getElementById('sdlogs-output');"
  "var sdLogsType='uart';"
  "var i2cScanBtn=document.getElementById('i2c-scan');"
  "var i2cStatus=document.getElementById('i2c-status');"
  "var i2cList=document.getElementById('i2c-list');"
  "var espnowMac1=document.getElementById('espnow-mac-1');"
  "var espnowMac2=document.getElementById('espnow-mac-2');"
  "var espnowSave1=document.getElementById('espnow-save-1');"
  "var espnowSave2=document.getElementById('espnow-save-2');"
  "var espnowReq1=document.getElementById('espnow-req-1');"
  "var espnowReq2=document.getElementById('espnow-req-2');"
  "var espnowStatus=document.getElementById('espnow-status');"
  "var espnowSelf=document.getElementById('espnow-self');"
  "var espnowChannel=document.getElementById('espnow-channel');"
  "var espnowAutoInterval=document.getElementById('espnow-auto-interval');"
  "var espnowAutoEnable=document.getElementById('espnow-auto-enable');"
  "var pcfInitialized=false;"
  "var isEditingBlowers=false;"
  "var a0Volts=document.getElementById('a0-volts');"
  "var a1Volts=document.getElementById('a1-volts');"
  "var consoleEl=document.getElementById('console');"
  "var consoleStatus=document.getElementById('console-status');"
  "var adsInitialized=false;"
  "var series={ph1:[],ph2:[],o21:[],o22:[],t1:[],t2:[],l1:[],l2:[]};"
  "var adsEnabledMask=0;"
  "var lastAnalog={enabledMask:0,channels:[]};"
  "var lastBlowers=null;"
  "var maxPoints=60;"

  "function pushPoint(key,val){var arr=series[key];arr.push(val);if(arr.length>maxPoints){arr.shift();}}"

  "function drawChart(canvasId,a,b,colorA,colorB){"
  "var canvas=document.getElementById(canvasId);if(!canvas){return;}"
  "var ctx=canvas.getContext('2d');var w=canvas.clientWidth;var h=canvas.clientHeight;"
  "canvas.width=w;canvas.height=h;ctx.clearRect(0,0,w,h);"
  "ctx.strokeStyle='#1f242b';ctx.lineWidth=1;ctx.strokeRect(0,0,w,h);"
  "function findMinMax(arrA,arrB){var min=Infinity;var max=-Infinity;"
  "for(var i=0;i<arrA.length;i++){if(arrA[i]<min){min=arrA[i];}if(arrA[i]>max){max=arrA[i];}}"
  "for(var j=0;j<arrB.length;j++){if(arrB[j]<min){min=arrB[j];}if(arrB[j]>max){max=arrB[j];}}"
  "if(min===Infinity){min=0;max=1;}if(min===max){min-=1;max+=1;}return {min:min,max:max};}"
  "var bounds=findMinMax(a,b);"
  "var leftPad=36;var rightPad=8;var topPad=8;var bottomPad=12;"
  "var plotW=w-leftPad-rightPad;var plotH=h-topPad-bottomPad;"
  "if(plotW<10||plotH<10){return;}"
  "ctx.strokeStyle='#2c333b';ctx.beginPath();ctx.moveTo(leftPad,topPad);"
  "ctx.lineTo(leftPad,topPad+plotH);ctx.stroke();"
  "ctx.fillStyle='#6f7b86';ctx.font='12px ui-sans-serif,system-ui';"
  "var tickCount=5;"
  "for(var t=0;t<tickCount;t++){"
  "var ratio=t/(tickCount-1);"
  "var y=topPad+((1-ratio)*plotH);"
  "var value=bounds.min+(ratio*(bounds.max-bounds.min));"
  "ctx.strokeStyle='#2c333b';ctx.beginPath();ctx.moveTo(leftPad-4,y);ctx.lineTo(leftPad,y);ctx.stroke();"
  "ctx.fillText(value.toFixed(2),2,y+4);"
  "}"
  "function drawLine(data,color){if(data.length<2){return;}ctx.strokeStyle=color;ctx.beginPath();"
  "for(var i=0;i<data.length;i++){var x=leftPad+(i*(plotW/(maxPoints-1)));"
  "var y=topPad+plotH-((data[i]-bounds.min)/(bounds.max-bounds.min))*plotH;"
  "if(i===0){ctx.moveTo(x,y);}else{ctx.lineTo(x,y);}}ctx.stroke();}"
  "drawLine(a,colorA);drawLine(b,colorB);"
  "}"

  "function updateCharts(){"
  "drawChart('chart-ph',series.ph1,series.ph2,'#67d4ff','#9ad9ff');"
  "drawChart('chart-o2',series.o21,series.o22,'#67d4ff','#9ad9ff');"
  "drawChart('chart-temp',series.t1,series.t2,'#67d4ff','#9ad9ff');"
  "drawChart('chart-level',series.l1,series.l2,'#67d4ff','#9ad9ff');"
  "}"

  "function updateCards(d){"
  "function fmt(v){return (v===null||!isFinite(v))?'--':v.toFixed(2);}"
  "ph1.textContent=fmt(d.phTank1);ph2.textContent=fmt(d.phTank2);"
  "o21.textContent=fmt(d.o2Tank1);o22.textContent=fmt(d.o2Tank2);"
  "t1.textContent=fmt(d.tempTank1);t2.textContent=fmt(d.tempTank2);"
  "l1.textContent=fmt(d.levelTank1);l2.textContent=fmt(d.levelTank2);"
  "blowerState.textContent=d.stateBlowers?'ON':'OFF';"
  "if(d.stateBlowers){blowerDot.classList.add('on');}else{blowerDot.classList.remove('on');}"
  "}"

  "function updateAds(mask,channels){"
  "adsEnabledMask=mask;"
  "lastAnalog={enabledMask:mask,channels:channels||[]};"
  "for(var i=0;i<4;i++){"
  "var toggle=document.querySelector('.ads-toggle[data-ch=\"'+i+'\"]');"
  "if(toggle){toggle.checked=(mask&(1<<i))!==0;}"
  "var vEl=document.getElementById('ads-v'+i);"
  "var rEl=document.getElementById('ads-r'+i);"
  "var ch=channels[i]||{};"
  "if(vEl){vEl.textContent=ch.valid?ch.volts.toFixed(3)+' V':'-- V';}"
  "if(rEl){rEl.textContent=ch.valid?('raw '+ch.raw):'raw --';}"
  "}"
  "if(!adsInitialized){initAdsToggles();adsInitialized=true;}"
  "updateBlowerIndicator();"
  "}"

  "function initAdsToggles(){"
  "var toggles=document.querySelectorAll('.ads-toggle');"
  "toggles.forEach(function(t){t.addEventListener('change',applyAdsMask);});"
  "}"

  "function applyAdsMask(){"
  "var mask=0;"
  "document.querySelectorAll('.ads-toggle').forEach(function(t){"
  "var ch=parseInt(t.getAttribute('data-ch'))||0;"
  "if(t.checked){mask|=(1<<ch);}"
  "});"
  "fetch('/api/analog/enable',{method:'POST',headers:{'Content-Type':'application/json'},"
  "body:JSON.stringify({enabledMask:mask})}).then(function(r){return r.json();})"
  ".then(function(d){if(d&&typeof d.enabledMask!=='undefined'){updateAds(d.enabledMask,[]);}});"
  "}"

  "function updateBlowers(d){"
  "lastBlowers=d;"
  "if(!isEditingBlowers){"
  "if(thrA0){thrA0.value=d.a0.threshold.toFixed(2);}"
  "if(thrA1){thrA1.value=d.a1.threshold.toFixed(2);}"
  "if(thrDelay){thrDelay.value=d.delaySec;}"
  "}"
  "if(blowerAlarm){blowerAlarm.checked=!!d.alarmEnabled;}"
  "if(a0Volts){a0Volts.textContent=(d.a0.valid?d.a0.volts.toFixed(3):'--')+' V';}"
  "if(a1Volts){a1Volts.textContent=(d.a1.valid?d.a1.volts.toFixed(3):'--')+' V';}"
  "updateBlowerIndicator();"
  "}"

  "function updateBlowerIndicator(){"
  "if(!lastBlowers){return;}"
  "var channels=lastAnalog.channels||[];"
  "var ch0=channels[0]||{};var ch1=channels[1]||{};"
  "var a0Enabled=(lastAnalog.enabledMask&0x01)!==0;"
  "var a1Enabled=(lastAnalog.enabledMask&0x02)!==0;"
  "var a0Ok=a0Enabled&&ch0.valid&&(ch0.volts>=lastBlowers.a0.threshold);"
  "var a1Ok=a1Enabled&&ch1.valid&&(ch1.volts>=lastBlowers.a1.threshold);"
  "var activeCount=(a0Enabled?1:0)+(a1Enabled?1:0);"
  "var okCount=(a0Ok?1:0)+(a1Ok?1:0);"
  "var indicatorOn=(activeCount>0)&&(okCount===activeCount);"
  "blowerState.textContent=indicatorOn?'ON':'OFF';"
  "blowerDot.classList.remove('on');blowerDot.classList.remove('warn');"
  "if(indicatorOn){blowerDot.classList.add('on');}"
  "}"

  "function setPcfState(el,value){"
  "if(!el){return;}"
  "if(value){el.classList.add('on');}else{el.classList.remove('on');}"
  "el.setAttribute('data-state',value?'1':'0');"
  "}"

  "function updatePcf(d){"
  "if(!d||!d.di||!d.do){return;}"
  "for(var i=0;i<8;i++){"
  "var inEl=Array.from(document.querySelectorAll('.pcf-in')).find(function(el){return el.getAttribute('data-pin')==i;});"
  "var outEl=Array.from(document.querySelectorAll('.pcf-out')).find(function(el){return el.getAttribute('data-pin')==i;});"
  "var inVal=!!d.di[i];var outVal=!!d.do[i];"
  "setPcfState(inEl,inVal);"
  "setPcfState(outEl,outVal);"
  "}"
  "if(!pcfInitialized){initPcfOutputs();pcfInitialized=true;}"
  "}"

  "function initPcfOutputs(){"
  "document.querySelectorAll('.pcf-out').forEach(function(btn){"
  "btn.addEventListener('click',function(){"
  "var pin=parseInt(btn.getAttribute('data-pin'))||0;"
  "var state=btn.getAttribute('data-state')==='1'?1:0;"
  "var next=state?0:1;"
  "postPcfDo(pin,next);"
  "});"
  "});"
  "}"

  "function postPcfDo(pin,value){"
  "fetch('/api/pcf/do',{method:'POST',headers:{'Content-Type':'application/json'},"
  "body:JSON.stringify({pin:pin,value:value})}).then(function(r){return r.json();})"
  ".then(function(d){if(d&&d.ok){fetchPcf();}});"
  "}"

  "function renderI2c(d){"
  "if(!i2cStatus||!i2cList){return;}"
  "if(!d||!d.ok){i2cStatus.textContent='error';i2cList.textContent='Scan failed';return;}"
  "var devices=d.devices||[];"
  "i2cStatus.textContent='ok';"
  "if(!devices.length){i2cList.textContent='No devices';return;}"
  "var labels=devices.map(function(addr){"
  "var hex=addr.toString(16).toUpperCase();"
  "if(hex.length<2){hex='0'+hex;}"
  "return '0x'+hex;"
  "});"
  "i2cList.textContent=labels.join(', ');"
  "}"

  "function scanI2c(){"
  "if(i2cStatus){i2cStatus.textContent='scanning...';}"
  "fetch('/api/i2c/scan').then(function(r){return r.json();}).then(function(d){renderI2c(d);})"
  ".catch(function(){if(i2cStatus){i2cStatus.textContent='error';}if(i2cList){i2cList.textContent='Scan failed';}});"
  "}"

  "function fetchEspNowConfig(){"
  "fetch('/api/espnow/config').then(function(r){return r.json();}).then(function(d){"
  "if(!d||!d.ok){return;}"
  "if(espnowMac1){espnowMac1.value=d.tank1||'';}"
  "if(espnowMac2){espnowMac2.value=d.tank2||'';}"
  "if(espnowSelf){espnowSelf.textContent=d.self||'--';}"
  "if(espnowChannel){espnowChannel.textContent=(d.channel!==undefined)?d.channel:'--';}"
  "});"
  "}"

  "function postEspNowConfig(tank,mac){"
  "if(espnowStatus){espnowStatus.textContent='saving...';}"
  "fetch('/api/espnow/config',{method:'POST',headers:{'Content-Type':'application/json'},"
  "body:JSON.stringify({tank:tank,mac:mac})}).then(function(r){return r.json();})"
  ".then(function(d){if(espnowStatus){espnowStatus.textContent=(d&&d.ok)?'saved':'error';}});"
  "}"

  "function requestEspNow(tank){"
  "if(espnowStatus){espnowStatus.textContent='requesting...';}"
  "fetch('/api/espnow/request',{method:'POST',headers:{'Content-Type':'application/json'},"
  "body:JSON.stringify({tank:tank})}).then(function(r){return r.json();})"
  ".then(function(d){if(espnowStatus){espnowStatus.textContent=(d&&d.ok)?'sent':'error';}});"
  "}"

  "function fetchEspNowAuto(){"
  "fetch('/api/espnow/auto').then(function(r){return r.json();}).then(function(d){"
  "if(!d||!d.ok){return;}"
  "if(espnowAutoInterval){espnowAutoInterval.value=d.intervalMin||5;}"
  "if(espnowAutoEnable){espnowAutoEnable.checked=!!d.enabled;}"
  "});"
  "}"

  "function postEspNowAuto(){"
  "if(!espnowAutoInterval||!espnowAutoEnable){return;}"
  "var interval=parseInt(espnowAutoInterval.value)||1;"
  "if(interval<1){interval=1;espnowAutoInterval.value=interval;}"
  "var enabled=espnowAutoEnable.checked?1:0;"
  "fetch('/api/espnow/auto',{method:'POST',headers:{'Content-Type':'application/json'},"
  "body:JSON.stringify({enabled:enabled,intervalMin:interval})}).then(function(r){return r.json();})"
  ".then(function(){fetchEspNowAuto();});"
  "}"

  "function postBlowers(){"
  "var a0=parseFloat(thrA0.value)||0;"
  "var a1=parseFloat(thrA1.value)||0;"
  "var delay=parseInt(thrDelay.value)||10;"
  "fetch('/api/blowers',{method:'POST',headers:{'Content-Type':'application/json'},"
  "body:JSON.stringify({a0:a0,a1:a1,delaySec:delay})}).then(function(r){return r.json();})"
  ".then(function(){isEditingBlowers=false;fetchBlowers();});"
  "}"

  "function postBlowerAlarm(){"
  "if(!blowerAlarm){return;}"
  "var enabled=blowerAlarm.checked?1:0;"
  "fetch('/api/blowers',{method:'POST',headers:{'Content-Type':'application/json'},"
  "body:JSON.stringify({alarmEnabled:enabled})}).then(function(r){return r.json();})"
  ".then(function(){fetchBlowers();});"
  "}"

  "function fetchBlowers(){"
  "fetch('/api/blowers').then(function(r){return r.json();}).then(function(d){updateBlowers(d);});"
  "}"

  "function fetchPcf(){"
  "fetch('/api/pcf/state').then(function(r){return r.json();}).then(function(d){updatePcf(d);});"
  "}"

  "function fetchDashboard(){"
  "fetch('/api/dashboard').then(function(r){return r.json();}).then(function(d){"
  "updateCards(d);"
  "if(d.phTank1!==null&&isFinite(d.phTank1)){pushPoint('ph1',d.phTank1);}"
  "if(d.phTank2!==null&&isFinite(d.phTank2)){pushPoint('ph2',d.phTank2);}"
  "if(d.o2Tank1!==null&&isFinite(d.o2Tank1)){pushPoint('o21',d.o2Tank1);}"
  "if(d.o2Tank2!==null&&isFinite(d.o2Tank2)){pushPoint('o22',d.o2Tank2);}"
  "if(d.tempTank1!==null&&isFinite(d.tempTank1)){pushPoint('t1',d.tempTank1);}"
  "if(d.tempTank2!==null&&isFinite(d.tempTank2)){pushPoint('t2',d.tempTank2);}"
  "if(d.levelTank1!==null&&isFinite(d.levelTank1)){pushPoint('l1',d.levelTank1);}"
  "if(d.levelTank2!==null&&isFinite(d.levelTank2)){pushPoint('l2',d.levelTank2);}"
  "updateCharts();"
  "lastUpdateEl.textContent='updated '+new Date().toLocaleTimeString();"
  "}).catch(function(){lastUpdateEl.textContent='update failed';});"
  "}"

  "function fetchAnalog(){"
  "fetch('/api/analog').then(function(r){return r.json();}).then(function(d){"
  "updateAds(d.enabledMask,d.channels||[]);"
  "});"
  "}"

  "function sendUart(op){"
  "fetch('/api/uart/cmd?op='+encodeURIComponent(op),{method:'POST'})"
  ".then(function(r){return r.json();})"
  ".then(function(d){if(!d||!d.ok){consoleEl.textContent+='UART error\\n';}})"
  ".catch(function(){consoleEl.textContent+='UART error\\n';});"
  "}"

  "function fetchUartAuto(){"
  "fetch('/api/uart/auto').then(function(r){return r.json();}).then(function(d){"
  "if(!d||!d.ok){return;}"
  "if(uartAutoInterval){uartAutoInterval.value=d.intervalMin||5;}"
  "if(uartAutoEnable){uartAutoEnable.checked=!!d.enabled;}"
  "});"
  "}"

  "function fetchUbidotsInterval(){"
  "fetch('/api/ubidots/interval').then(function(r){return r.json();}).then(function(d){"
  "if(!d||!d.ok){return;}"
  "if(ubidotsInterval){ubidotsInterval.value=d.intervalMin||5;}"
  "});"
  "}"

  "function fetchClock(){"
  "fetch('/api/time').then(function(r){return r.json();}).then(function(d){"
  "if(!d||!d.ok){return;}"
  "if(clockTime){clockTime.textContent=d.local||'--';}"
  "if(clockStatus){clockStatus.textContent=d.synced?'synced':'sync pending';}"
  "});"
  "}"

  "function setSdLogsType(type){"
  "sdLogsType=type;"
  "if(sdLogsUart){sdLogsUart.classList.toggle('active',type==='uart');}"
  "if(sdLogsLevel){sdLogsLevel.classList.toggle('active',type==='level');}"
  "}"

  "function fetchSdLogs(){"
  "if(!sdLogsOutput){return;}"
  "fetch('/api/sd/logs?type='+sdLogsType).then(function(r){return r.json();}).then(function(d){"
  "if(!d||!d.ok){sdLogsOutput.textContent='--';return;}"
  "sdLogsOutput.textContent=(d.lines||[]).join('\\n')||'--';"
  "});"
  "}"

  "function clearSdLogs(){"
  "if(!confirm('Clear all logs in /logs?')){return;}"
  "fetch('/api/sd/clear',{method:'POST'}).then(function(r){return r.json();}).then(function(){fetchSdLogs();});"
  "}"


  "function postUbidotsInterval(){"
  "if(!ubidotsInterval){return;}"
  "var interval=parseInt(ubidotsInterval.value)||1;"
  "if(interval<1){interval=1;ubidotsInterval.value=interval;}"
  "fetch('/api/ubidots/interval',{method:'POST',headers:{'Content-Type':'application/json'},"
  "body:JSON.stringify({intervalMin:interval})}).then(function(r){return r.json();})"
  ".then(function(d){if(d&&d.intervalMin!==undefined&&ubidotsInterval){ubidotsInterval.value=d.intervalMin;}});"
  "}"

  "function postUartAuto(){"
  "if(!uartAutoInterval||!uartAutoEnable){return;}"
  "var interval=parseInt(uartAutoInterval.value)||1;"
  "if(interval<1){interval=1;uartAutoInterval.value=interval;}"
  "var enabled=uartAutoEnable.checked?1:0;"
  "fetch('/api/uart/auto',{method:'POST',headers:{'Content-Type':'application/json'},"
  "body:JSON.stringify({enabled:enabled,intervalMin:interval})}).then(function(r){return r.json();})"
  ".then(function(){fetchUartAuto();});"
  "}"

  "var ws=new WebSocket('ws://'+location.hostname+':81/');"
  "ws.onopen=function(){consoleStatus.textContent='connected';};"
  "ws.onerror=function(){consoleStatus.textContent='error';};"
  "ws.onclose=function(){consoleStatus.textContent='disconnected';};"
  "ws.onmessage=function(e){if(consoleEl.textContent==='Waiting for messages...'){consoleEl.textContent='';}"
  "consoleEl.textContent+=e.data+'\\n';consoleEl.scrollTop=consoleEl.scrollHeight;};"

  "fetchDashboard();fetchAnalog();fetchBlowers();"
  "fetchPcf();"
  "fetchEspNowConfig();"
  "fetchUartAuto();"
  "fetchUbidotsInterval();"
  "fetchClock();"
  "fetchEspNowAuto();"
  "setSdLogsType('uart');"
  "setInterval(fetchDashboard,2000);"
  "setInterval(fetchAnalog,2000);"
  "setInterval(fetchBlowers,2000);"
  "setInterval(fetchPcf,1000);"
  "setInterval(fetchClock,5000);"
  "if(thrA0){thrA0.addEventListener('focus',function(){isEditingBlowers=true;});}"
  "if(thrA1){thrA1.addEventListener('focus',function(){isEditingBlowers=true;});}"
  "if(thrDelay){thrDelay.addEventListener('focus',function(){isEditingBlowers=true;});}"
  "if(thrApply){thrApply.addEventListener('click',postBlowers);}"
  "if(blowerAlarm){blowerAlarm.addEventListener('change',postBlowerAlarm);}"
  "if(uartGetStatus){uartGetStatus.addEventListener('click',function(){sendUart('get_status');});}"
  "if(uartGetLast){uartGetLast.addEventListener('click',function(){sendUart('get_last');});}"
  "if(uartAuto){uartAuto.addEventListener('click',function(){sendUart('auto_measure');});}"
  "if(uartAutoInterval){uartAutoInterval.addEventListener('change',postUartAuto);}"
  "if(uartAutoEnable){uartAutoEnable.addEventListener('change',postUartAuto);}"
  "if(ubidotsApply){ubidotsApply.addEventListener('click',postUbidotsInterval);}"
  "if(sdLogsUart){sdLogsUart.addEventListener('click',function(){setSdLogsType('uart');fetchSdLogs();});}"
  "if(sdLogsLevel){sdLogsLevel.addEventListener('click',function(){setSdLogsType('level');fetchSdLogs();});}"
  "if(sdLogsRefresh){sdLogsRefresh.addEventListener('click',fetchSdLogs);}"
  "if(sdLogsClear){sdLogsClear.addEventListener('click',clearSdLogs);}"
  "if(i2cScanBtn){i2cScanBtn.addEventListener('click',scanI2c);}"
  "if(espnowSave1&&espnowMac1){espnowSave1.addEventListener('click',function(){postEspNowConfig(1,espnowMac1.value);});}"
  "if(espnowSave2&&espnowMac2){espnowSave2.addEventListener('click',function(){postEspNowConfig(2,espnowMac2.value);});}"
  "if(espnowReq1){espnowReq1.addEventListener('click',function(){requestEspNow(1);});}"
  "if(espnowReq2){espnowReq2.addEventListener('click',function(){requestEspNow(2);});}"
  "if(espnowAutoInterval){espnowAutoInterval.addEventListener('change',postEspNowAuto);}"
  "if(espnowAutoEnable){espnowAutoEnable.addEventListener('change',postEspNowAuto);}"
  "</script>";
