#pragma once

static const char kDashboardStyle[] =
  "<style>"
  ":root{--bg:#0f1114;--panel:#15191e;--card:#1a1f25;--muted:#9aa4ad;--text:#e7ecef;"
  "--accent:#67d4ff;--ok:#47d17c;--warn:#f5b24a;}"
  "*{box-sizing:border-box;}"
  "body{margin:0;background:var(--bg);color:var(--text);font-family:ui-monospace,SFMono-Regular,"
  "Menlo,Monaco,Consolas,'Liberation Mono','Courier New',monospace;}"
  "header{padding:16px 20px;border-bottom:1px solid #222830;display:flex;align-items:center;"
  "justify-content:space-between;background:#0e1216;position:sticky;top:0;z-index:5;}"
  "header h1{margin:0;font-size:16px;letter-spacing:0.08em;text-transform:uppercase;color:var(--muted);}"
  ".status{font-size:12px;color:var(--muted);}"
  "main{padding:18px 20px 0;}"
  ".cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px;}"
  ".card{background:var(--card);border:1px solid #242a2f;border-radius:10px;padding:12px;"
  "box-shadow:0 10px 25px rgba(0,0,0,0.25);}"
  ".card h3{margin:0 0 8px 0;font-size:12px;color:var(--muted);text-transform:uppercase;letter-spacing:0.06em;}"
  ".metric{display:flex;justify-content:space-between;align-items:center;margin:4px 0;font-size:14px;}"
  ".metric span{color:var(--muted);}"
  ".blowers{display:flex;align-items:center;gap:8px;font-size:14px;}"
  ".dot{width:10px;height:10px;border-radius:50%;background:var(--warn);}"
  ".dot.on{background:var(--ok);}"
  ".dot.warn{background:var(--warn);}"
  ".blower-inputs{display:flex;align-items:center;justify-content:space-between;"
  "margin-top:6px;gap:8px;font-size:12px;}"
  ".blower-inputs label{display:flex;flex-direction:column;gap:4px;color:var(--muted);}"
  ".blower-inputs input{background:#11161b;border:1px solid #242a2f;color:var(--text);"
  "border-radius:6px;padding:4px 6px;width:120px;}"
  ".alarm-toggle{flex-direction:row;align-items:center;gap:8px;}"
  ".alarm-toggle input{width:auto;}"
  ".blower-actions{display:flex;justify-content:flex-end;margin-top:8px;}"
  ".blower-actions button{background:#1b2228;border:1px solid #242a2f;color:var(--text);"
  "padding:6px 10px;border-radius:6px;cursor:pointer;font-size:12px;}"
  ".blower-actions button:hover{background:#232a31;}"
  ".ads-card{grid-column:span 2;}"
  ".ads-row{display:grid;grid-template-columns:64px 1fr 1fr;gap:8px;align-items:center;"
  "font-size:12px;margin:6px 0;}"
  ".ads-row label{display:flex;align-items:center;gap:6px;color:var(--muted);}"
  ".ads-val{color:var(--accent);font-weight:600;}"
  ".ads-raw{color:var(--muted);text-align:right;}"
  ".uart-card{grid-column:span 2;}"
  ".uart-actions{display:flex;gap:8px;flex-wrap:wrap;}"
  ".uart-actions button{background:#1b2228;border:1px solid #242a2f;color:var(--text);"
  "padding:6px 10px;border-radius:6px;cursor:pointer;font-size:12px;}"
  ".uart-actions button:hover{background:#232a31;}"
  ".uart-auto{display:flex;gap:10px;align-items:flex-end;margin-top:8px;flex-wrap:wrap;}"
  ".uart-auto label{display:flex;flex-direction:column;gap:4px;color:var(--muted);font-size:11px;}"
  ".uart-auto input{background:#11161b;border:1px solid #242a2f;color:var(--text);"
  "border-radius:6px;padding:4px 6px;width:120px;}"
  ".uart-toggle{flex-direction:row;align-items:center;gap:8px;}"
  ".uart-toggle input{width:auto;}"
  ".uart-note{margin-top:8px;color:var(--muted);font-size:11px;}"
  ".clock-card{grid-column:span 2;}"
  ".clock-time{font-size:18px;font-weight:600;color:var(--accent);letter-spacing:0.02em;}"
  ".clock-status{margin-top:6px;color:var(--muted);font-size:11px;}"
  ".sdlogs-card{grid-column:span 2;}"
  ".sdlogs-actions{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:8px;}"
  ".sdlogs-actions button{background:#1b2228;border:1px solid #242a2f;color:var(--text);"
  "padding:6px 10px;border-radius:6px;cursor:pointer;font-size:12px;}"
  ".sdlogs-actions button:hover{background:#232a31;}"
  ".sdlogs-actions button.active{border-color:var(--accent);color:var(--accent);}"
  ".sdlogs-output{background:#11161b;border:1px solid #242a2f;border-radius:6px;"
  "padding:8px;font-size:11px;color:var(--text);min-height:96px;white-space:pre-wrap;}"
  ".ubidots-card{grid-column:span 2;}"
  ".wdt-card{grid-column:span 2;}"
  ".wdt-row{display:flex;gap:10px;align-items:flex-end;flex-wrap:wrap;}"
  ".wdt-row label{display:flex;flex-direction:column;gap:4px;color:var(--muted);font-size:11px;}"
  ".wdt-row input{background:#11161b;border:1px solid #242a2f;color:var(--text);"
  "border-radius:6px;padding:4px 6px;width:120px;}"
  ".wdt-row button{background:#1b2228;border:1px solid #242a2f;color:var(--text);"
  "padding:6px 10px;border-radius:6px;cursor:pointer;font-size:12px;}"
  ".wdt-row button:hover{background:#232a31;}"
  ".wifi-card{grid-column:span 2;}"
  ".wifi-row{display:flex;gap:10px;align-items:flex-end;flex-wrap:wrap;}"
  ".wifi-row label{display:flex;flex-direction:column;gap:4px;color:var(--muted);font-size:11px;}"
  ".wifi-row input{background:#11161b;border:1px solid #242a2f;color:var(--text);"
  "border-radius:6px;padding:4px 6px;width:180px;}"
  ".wifi-toggle{display:flex;align-items:center;gap:6px;color:var(--muted);font-size:11px;}"
  ".wifi-toggle input{width:auto;}"
  ".wifi-row button{background:#1b2228;border:1px solid #242a2f;color:var(--text);"
  "padding:6px 10px;border-radius:6px;cursor:pointer;font-size:12px;}"
  ".wifi-row button:hover{background:#232a31;}"
  ".ubidots-row{display:flex;gap:10px;align-items:flex-end;flex-wrap:wrap;}"
  ".ubidots-row label{display:flex;flex-direction:column;gap:4px;color:var(--muted);font-size:11px;}"
  ".ubidots-row input{background:#11161b;border:1px solid #242a2f;color:var(--text);"
  "border-radius:6px;padding:4px 6px;width:120px;}"
  ".ubidots-row button{background:#1b2228;border:1px solid #242a2f;color:var(--text);"
  "padding:6px 10px;border-radius:6px;cursor:pointer;font-size:12px;}"
  ".ubidots-row button:hover{background:#232a31;}"
  ".pcf-card{grid-column:span 2;}"
  ".pcf-block{margin-top:6px;}"
  ".pcf-title{font-size:11px;color:var(--muted);text-transform:uppercase;letter-spacing:0.06em;margin-bottom:6px;}"
  ".pcf-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:6px;}"
  ".pcf-io{display:flex;align-items:center;justify-content:space-between;gap:8px;"
  "background:#11161b;border:1px solid #242a2f;color:var(--text);padding:6px 8px;border-radius:6px;"
  "font-size:12px;}"
  ".pcf-io span{color:var(--muted);}"
  ".pcf-io.on span{color:var(--text);}"
  ".pcf-out{cursor:pointer;}"
  ".pcf-out:hover{background:#192026;}"
  ".pcf-dot{width:10px;height:10px;border-radius:50%;background:#3a444f;}"
  ".pcf-io.on .pcf-dot{background:var(--ok);}"
  ".i2c-card{grid-column:span 2;}"
  ".i2c-row{display:flex;align-items:center;gap:10px;margin-bottom:8px;}"
  ".i2c-row button{background:#1b2228;border:1px solid #242a2f;color:var(--text);"
  "padding:6px 10px;border-radius:6px;cursor:pointer;font-size:12px;}"
  ".i2c-row button:hover{background:#232a31;}"
  ".i2c-status{font-size:11px;color:var(--muted);}"
  ".i2c-list{background:#11161b;border:1px solid #242a2f;border-radius:6px;"
  "padding:8px;font-size:12px;color:var(--text);min-height:32px;}"
  ".espnow-card{grid-column:span 2;}"
  ".espnow-row{display:grid;grid-template-columns:1fr auto auto;gap:8px;align-items:end;margin-bottom:8px;}"
  ".espnow-row label{display:flex;flex-direction:column;gap:4px;color:var(--muted);font-size:11px;}"
  ".espnow-row input{background:#11161b;border:1px solid #242a2f;color:var(--text);"
  "border-radius:6px;padding:4px 6px;width:100%;}"
  ".espnow-row button{background:#1b2228;border:1px solid #242a2f;color:var(--text);"
  "padding:6px 10px;border-radius:6px;cursor:pointer;font-size:12px;}"
  ".espnow-row button:hover{background:#232a31;}"
  ".espnow-self{font-size:11px;color:var(--muted);margin-bottom:6px;}"
  ".espnow-self span{color:var(--text);}"
  ".espnow-auto{display:flex;gap:10px;align-items:flex-end;margin:6px 0 8px;flex-wrap:wrap;}"
  ".espnow-auto label{display:flex;flex-direction:column;gap:4px;color:var(--muted);font-size:11px;}"
  ".espnow-auto input{background:#11161b;border:1px solid #242a2f;color:var(--text);"
  "border-radius:6px;padding:4px 6px;width:120px;}"
  ".espnow-toggle{flex-direction:row;align-items:center;gap:8px;}"
  ".espnow-toggle input{width:auto;}"
  ".espnow-status{font-size:11px;color:var(--muted);}"
  ".charts{display:grid;grid-template-columns:repeat(auto-fit,minmax(320px,1fr));gap:12px;margin-top:16px;}"
  ".chart{background:var(--panel);border:1px solid #242a2f;border-radius:10px;padding:12px;position:relative;}"
  ".chart h4{margin:0 0 6px 0;font-size:12px;color:var(--muted);text-transform:uppercase;letter-spacing:0.06em;}"
  ".legend{display:flex;gap:10px;flex-wrap:wrap;font-size:11px;color:var(--muted);margin-bottom:6px;}"
  ".legend-item{display:flex;align-items:center;gap:6px;}"
  ".swatch{width:10px;height:10px;border-radius:50%;display:inline-block;}"
  ".swatch-a{background:#67d4ff;}"
  ".swatch-b{background:#9ad9ff;}"
  "canvas{width:100%;height:160px;background:#0f1318;border-radius:6px;}"
  ".console-wrap{margin-top:18px;border-top:1px solid #222830;background:#0b0d10;padding:12px 20px 18px;}"
  ".console-head{display:flex;align-items:center;justify-content:space-between;color:var(--muted);"
  "font-size:12px;margin-bottom:8px;}"
  "#console{height:220px;overflow:auto;background:#0f1216;border:1px solid #242a2f;border-radius:8px;"
  "padding:10px;white-space:pre-wrap;font-size:12px;}"
  "</style>";
