#pragma once

static const char kDashboardScript[] =
  "<script>"
  "var lastUpdateEl=document.getElementById('last-update');"
  "var ph1=document.getElementById('ph1');var ph2=document.getElementById('ph2');"
  "var o21=document.getElementById('o21');var o22=document.getElementById('o22');"
  "var t1=document.getElementById('t1');var t2=document.getElementById('t2');"
  "var l1=document.getElementById('l1');var l2=document.getElementById('l2');"
  "var blowerDot=document.getElementById('blower-dot');"
  "var blowerState=document.getElementById('blower-state');"
  "var consoleEl=document.getElementById('console');"
  "var consoleStatus=document.getElementById('console-status');"
  "var adsInitialized=false;"
  "var series={ph1:[],ph2:[],o21:[],o22:[],t1:[],t2:[],l1:[],l2:[]};"
  "var maxPoints=60;"

  "function pushPoint(key,val){var arr=series[key];arr.push(val);if(arr.length>maxPoints){arr.shift();}}"

  "function drawChart(canvasId,a,b,colorA,colorB){"
  "var canvas=document.getElementById(canvasId);"
  "if(!canvas){return;}"
  "var ctx=canvas.getContext('2d');"
  "var w=canvas.clientWidth;var h=canvas.clientHeight;"
  "canvas.width=w;canvas.height=h;"
  "ctx.clearRect(0,0,w,h);"
  "ctx.strokeStyle='#1f242b';ctx.lineWidth=1;ctx.strokeRect(0,0,w,h);"
  "function findMinMax(arrA,arrB){"
  "var min=Infinity;var max=-Infinity;"
  "for(var i=0;i<arrA.length;i++){if(arrA[i]<min){min=arrA[i];}if(arrA[i]>max){max=arrA[i];}}"
  "for(var j=0;j<arrB.length;j++){if(arrB[j]<min){min=arrB[j];}if(arrB[j]>max){max=arrB[j];}}"
  "if(min===Infinity){min=0;max=1;}"
  "if(min===max){min-=1;max+=1;}"
  "return {min:min,max:max};"
  "}"
  "var bounds=findMinMax(a,b);"
  "function drawLine(data,color){"
  "if(data.length<2){return;}"
  "ctx.strokeStyle=color;ctx.beginPath();"
  "for(var i=0;i<data.length;i++){"
  "var x=i*(w/(maxPoints-1));"
  "var y=h-((data[i]-bounds.min)/(bounds.max-bounds.min))*h;"
  "if(i===0){ctx.moveTo(x,y);}else{ctx.lineTo(x,y);}"
  "}ctx.stroke();"
  "}"
  "drawLine(a,colorA);drawLine(b,colorB);"
  "}"

  "function updateCharts(){"
  "drawChart('chart-ph',series.ph1,series.ph2,'#67d4ff','#9ad9ff');"
  "drawChart('chart-o2',series.o21,series.o22,'#67d4ff','#9ad9ff');"
  "drawChart('chart-temp',series.t1,series.t2,'#67d4ff','#9ad9ff');"
  "drawChart('chart-level',series.l1,series.l2,'#67d4ff','#9ad9ff');"
  "}"

  "function updateCards(d){"
  "ph1.textContent=d.phTank1.toFixed(2);ph2.textContent=d.phTank2.toFixed(2);"
  "o21.textContent=d.o2Tank1.toFixed(2);o22.textContent=d.o2Tank2.toFixed(2);"
  "t1.textContent=d.tempTank1.toFixed(2);t2.textContent=d.tempTank2.toFixed(2);"
  "l1.textContent=d.levelTank1.toFixed(2);l2.textContent=d.levelTank2.toFixed(2);"
  "blowerState.textContent=d.stateBlowers?'ON':'OFF';"
  "if(d.stateBlowers){blowerDot.classList.add('on');}else{blowerDot.classList.remove('on');}"
  "}"

  "function fetchDashboard(){"
  "fetch('/api/dashboard').then(function(r){return r.json();}).then(function(d){"
  "updateCards(d);"
  "pushPoint('ph1',d.phTank1);pushPoint('ph2',d.phTank2);"
  "pushPoint('o21',d.o2Tank1);pushPoint('o22',d.o2Tank2);"
  "pushPoint('t1',d.tempTank1);pushPoint('t2',d.tempTank2);"
  "pushPoint('l1',d.levelTank1);pushPoint('l2',d.levelTank2);"
  "updateCharts();"
  "lastUpdateEl.textContent='updated '+new Date().toLocaleTimeString();"
  "}).catch(function(){lastUpdateEl.textContent='update failed';});"
  "}"

  "function updateAds(mask,channels){"
  "for(var i=0;i<4;i++){"
  "var toggle=document.querySelector('.ads-toggle[data-ch=\"'+i+'\"]');"
  "if(toggle){toggle.checked=(mask&(1<<i))!==0;}"
  "var vEl=document.getElementById('ads-v'+i);"
  "var rEl=document.getElementById('ads-r'+i);"
  "var ch=channels[i]||{};"
  "if(vEl){vEl.textContent=ch.valid?ch.volts.toFixed(3)+' V':'-- V';}"
  "if(rEl){rEl.textContent=ch.valid?('raw '+ch.raw):'raw --';}"
  "}"
  "if(!adsInitialized){initAdsToggles();adsInitialized=true;}"
  "}"

  "function initAdsToggles(){"
  "var toggles=document.querySelectorAll('.ads-toggle');"
  "toggles.forEach(function(t){t.addEventListener('change',applyAdsMask);});"
  "}"

  "function applyAdsMask(){"
  "var mask=0;"
  "document.querySelectorAll('.ads-toggle').forEach(function(t){"
  "var ch=parseInt(t.getAttribute('data-ch'))||0;"
  "if(t.checked){mask|=(1<<ch);}"
  "});"
  "fetch('/api/analog/enable',{method:'POST',headers:{'Content-Type':'application/json'},"
  "body:JSON.stringify({enabledMask:mask})}).then(function(r){return r.json();})"
  ".then(function(d){if(d&&typeof d.enabledMask!=='undefined'){updateAds(d.enabledMask,[]);}});"
  "}"

  "function fetchAnalog(){"
  "fetch('/api/analog').then(function(r){return r.json();}).then(function(d){"
  "updateAds(d.enabledMask,d.channels||[]);"
  "});"
  "}"

  "var ws=new WebSocket('ws://'+location.hostname+':81/');"
  "ws.onopen=function(){consoleStatus.textContent='connected';};"
  "ws.onerror=function(){consoleStatus.textContent='error';};"
  "ws.onclose=function(){consoleStatus.textContent='disconnected';};"
  "ws.onmessage=function(e){if(consoleEl.textContent==='Waiting for messages...'){consoleEl.textContent='';}"
  "consoleEl.textContent+=e.data+'\\n';consoleEl.scrollTop=consoleEl.scrollHeight;};"

  "fetchDashboard();"
  "fetchAnalog();"
  "setInterval(fetchDashboard,2000);"
  "setInterval(fetchAnalog,2000);"
  "</script>";
